name: 'Project Setup'

on:
  workflow_dispatch:
    inputs:
      user_repo:
        description: "Repository with user project code"
        required: true
        default: "project-template"

      user_cache:
        description: "Commit SHA of project code"
        required: false

env:
  TEST_REPO: "project-tests"
  TEST_PATH: "project-tests"
  USER_PATH: "project-main"

jobs:
  results:
    runs-on: ubuntu-latest
    name: Project Setup
 
    steps:
      - name: Get Test Commit SHA
        id: test-commit
        uses: actions/github-script@v6
        env:
          REPO_NAME: "${{ env.TEST_REPO }}"
        with:
          result-encoding: string
          script: |
            const params = {
              owner: context.repo.owner,
              repo: process.env.REPO_NAME,
              per_page: 1
            };

            const result = await github.rest.repos.listCommits(params);

            if (result.status === 200 && result.data.length === 1) {
              const sha = result.data[0].sha;
              core.info(`sha: ${sha}`);
              return sha;
            }

            core.info(`params: ${JSON.stringify(params)}`);
            core.info(`result: ${JSON.stringify(result)}`);
            core.setFailed(`Unable to find commit SHA for: ${process.env.REPO_NAME}`);

      - name: Get Code Commit SHA
        id: code-commit
        uses: actions/github-script@v6
        if: ${{ inputs.user_cache == '' }}
        env:
          REPO_NAME: "${{ inputs.user_repo }}"
        with:
          result-encoding: string
          script: |
            const params = {
              owner: context.repo.owner,
              repo: process.env.REPO_NAME,
              per_page: 1
            };

            const result = await github.rest.repos.listCommits(params);

            if (result.status === 200 && result.data.length === 1) {
              const sha = result.data[0].sha;
              core.info(`sha: ${sha}`);
              return sha;
            }

            core.info(`params: ${JSON.stringify(params)}`);
            core.info(`result: ${JSON.stringify(result)}`);
            core.setFailed(`Unable to find commit SHA for: ${process.env.REPO_NAME}`);

      - name: Setup Project
        id: setup-project
        uses: usf-cs272-fall2022/action-project-setup@main
        with:
          user_repo:  "${{ inputs.user_repo }}"
          user_cache: "${{ steps.code-commit.outputs.result }}"
          test_cache: "${{ steps.test-commit.outputs.result }}"
          test_repo:  "${{ env.TEST_REPO }}"
          test_path:  "${{ env.TEST_PATH }}"
          user_path:  "${{ env.USER_PATH }}"
